### ISSUE TITLE
citation is wrong

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [StructuralEquationModels/StructuralEquationModels.jl#107]
citing our package produces
, M. S., Ernst, & Peikert, A. StructuralEquationModels.jl [Computer software]. https://github.com/StructuralEquationModels/StructuralEquationModels.jl

while it should be
Ernst, M.S. & Peikert, A. StructuralEquationModels.jl [Computer software]. https://github.com/StructuralEquationModels/StructuralEquationModels.jl

**Comment by aaronpeikert** [comment]
Mh... It was when I checked a few minutes ago. Anyways, you had this weird "name suffix" thing instead of family name so I changed that.

**Comment by aaronpeikert** [comment]
![image](https://user-images.githubusercontent.com/29424409/174031297-7151e049-dbb1-4829-b661-fb7839f15c43.png)

**Comment by aaronpeikert** [comment]
5b042b1
