### ISSUE TITLE
What types of models do not need an imply?

### ISSUE THREAD

**Issue by aaronpeikert** [StructuralEquationModels/StructuralEquationModels.jl#108]
@Maximilian-Stefan-Ernst Could you elaborate?

https://github.com/StructuralEquationModels/StructuralEquationModels.jl/blob/0c187846c92ec7ce66c7f590a9a8caa466da1445/src/imply/empty.jl#L5

**Comment by Maximilian-Stefan-Ernst** [comment]
For example, a multigroup model with ridge regularization can be implemented as one model per group plus one additional model for the regularization. The regularization model does not need an imply part, as ridge does not depend on the model implied covariance matrix. Do you think that should be part of the documentation there?

**Comment by aaronpeikert** [comment]
Yes.

**Comment by Maximilian-Stefan-Ernst** [comment]
Ok, I will add it
