### ISSUE TITLE
Usage for social research

### ISSUE THREAD

**Issue by anggoran** [StructuralEquationModels/StructuralEquationModels.jl#154]
Could the Julia package be used for social research like replacing SmartPLS or Lisrel, in terms of functionality?

**Comment by Maximilian-Stefan-Ernst** [comment]
Hi, sorry for the late reply (I get too many mails from GitHub every day, so I missed your issue) - I don't know about SmartPLS, but many models that can be estimated in Lisrel can also be estimated with our package. Do you have a specific model / type of model in mind?

**Comment by anggoran** [comment]
If I'm not mistaken, SmartPLS adopts Variance Based SEM, while LISREL is Covariance-Based SEM. I don't really know how different both in statistical equations, but these two are popularly used at least in social research like marketing and psychology papers

**Comment by Maximilian-Stefan-Ernst** [comment]
Okay, so our package is able to estimate many models that can be estimated with LISREL, but SmartPLS uses partial least squares estimators which is not in the scope of this package (since it follows a different modeling philosophy).
