### ISSUE TITLE
Update for new version dependencies

### ISSUE THREAD

**Issue by veroyatnost** [StructuralEquationModels/StructuralEquationModels.jl#161]
ERROR: Unsatisfiable requirements detected for package PrettyTables [08abe8d2]:
 PrettyTables [08abe8d2] log:
 ├─possible versions are: 0.1.0-2.3.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-2.3.1
 ├─restricted by compatibility requirements with StructuralEquationModels [383ca8c5] to versions: 1.0.0-1.3.1
 │ └─StructuralEquationModels [383ca8c5] log:
 │   ├─possible versions are: 0.1.0-0.2.1 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.2.1
 └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 2.1.0-2.3.1 — no versions left
   └─DataFrames [a93c6f00] log:
     ├─possible versions are: 0.11.7-1.6.1 or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions: 0.11.7-1.6.1
     ├─restricted by compatibility requirements with StructuralEquationModels [383ca8c5] to versions: 1.0.0-1.6.1
     │ └─StructuralEquationModels [383ca8c5] log: see above
     └─restricted by compatibility requirements with TidierData [fe2206b3] to versions: 1.5.0-1.6.1
       └─TidierData [fe2206b3] log:
         ├─possible versions are: 0.8.0-0.14.4 or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions: 0.8.0-0.14.4
Stacktrace:
  [1] propagate_constraints!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; log_events::Bool)
    @ Pkg.Resolve /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1072
  [2] propagate_constraints! (repeats 2 times)
    @ Pkg.Resolve /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1008 [inlined]
  [3] simplify_graph!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; clean_graph::Bool)
    @ Pkg.Resolve /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1533
  [4] simplify_graph! (repeats 2 times)
    @ Pkg.Resolve /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1532 [inlined]
  [5] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{…}, pkgs::Vector{…}, julia_version::VersionNumber, installed_only::Bool)
    @ Pkg.Operations /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:407
  [6] targeted_resolve(env::Pkg.Types.EnvCache, registries::Vector{…}, pkgs::Vector{…}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1360
  [7] tiered_resolve(env::Pkg.Types.EnvCache, registries::Vector{…}, pkgs::Vector{…}, julia_version::VersionNumber, try_all_installed::Bool)
    @ Pkg.Operations /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1349
  [8] _resolve(io::Base.TTY, env::Pkg.Types.EnvCache, registries::Vector{…}, pkgs::Vector{…}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1370
  [9] add(ctx::Pkg.Types.Context, pkgs::Vector{…}, new_git::Set{…}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1387
 [10] add
    @ Pkg.Operations /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1376 [inlined]
 [11] add(ctx::Pkg.Types.Context, pkgs::Vector{…}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::@Kwargs{…})
    @ Pkg.API /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:278
 [12] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::@Kwargs{})
    @ Pkg.API /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:159
 [13] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:148
 [14] add
    @ Pkg.API /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:147 [inlined]
 [15] add(pkg::String)
    @ Pkg.API /Applications/Julia-1.10.0.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:146
 [16] top-level scope
    @ REPL[19]:1

**Comment by Maximilian-Stefan-Ernst** [comment]
Thanks a lot! I will look into this...

**Comment by Maximilian-Stefan-Ernst** [comment]
I updated the dependencies, it should work now - maybe you can tell me if it also works for you?

**Comment by veroyatnost** [comment]
> I updated the dependencies, it should work now - maybe you can tell me if it also works for you?

Thanks for your rapid fix, but it could not pass precompile. I attached the error report. Perhaps it is associated with the dependencies Symbolics and SymbolicUtils.


in expression starting at stdin:3
  ✗ SymbolicUtils
  ✗ Symbolics
  ✗ StructuralEquationModels
  0 dependencies successfully precompiled in 10 seconds. 145 already precompiled.

ERROR: The following 3 direct dependencies failed to precompile:

SymbolicUtils [d1185830-fcd6-423d-90d6-eec64667417b]

Failed to precompile SymbolicUtils [d1185830-fcd6-423d-90d6-eec64667417b] to "/Users/chenhaoyu/.julia/compiled/v1.10/SymbolicUtils/jl_MMLMX3".
ERROR: LoadError: UndefVarError: `nodevalue` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ ~/.julia/packages/SymbolicUtils/ssQsQ/src/inspect.jl:4
 [3] include(mod::Module, _path::String)
   @ Base ./Base.jl:495
 [4] include(x::String)
   @ SymbolicUtils ~/.julia/packages/SymbolicUtils/ssQsQ/src/SymbolicUtils.jl:4
 [5] top-level scope
   @ ~/.julia/packages/SymbolicUtils/ssQsQ/src/SymbolicUtils.jl:31
 [6] include
   @ Base ./Base.jl:495 [inlined]
 [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2216
 [8] top-level scope
   @ stdin:3
in expression starting at ~/.julia/packages/SymbolicUtils/ssQsQ/src/inspect.jl:4
in expression starting at ~/.julia/packages/SymbolicUtils/ssQsQ/src/SymbolicUtils.jl:1
in expression starting at stdin:3
Symbolics [0c5d862f-8b57-4792-8d23-62f2024744c7]

**Comment by veroyatnost** [comment]
Based on the latest document, add by:
```Julia
]
add StructuralEquationModels
```
It workds

**Comment by Maximilian-Stefan-Ernst** [comment]
Ah, weird precompilation error... thanks for reporting.

**Comment by veroyatnost** [comment]
> Ah, weird precompilation error... thanks for reporting.

With one more word, I believe that the document in the stable version is not proper for installation, the dev version one works.
This Works 
```Julia
julia> ]
pkg> add StructuralEquationModels
```

This not worked on 10/Jan/2024
```Julia
using Pkg
Pkg.add(url = "https://github.com/StructuralEquationModels/StructuralEquationModels.jl")
```
